<?php
$v_params = $this->getParams();
$o_contato = $v_params['o_contato'];
$v_telefones = $v_params['v_telefones'];
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>
        Agenda Tele&ocirc;nica - Exemplo de MVC com PHP
    </title>
    <link rel="stylesheet" type="text/css" href="estilo.css" />
</head>
<body>
    <div  id="tblcontc" align="center">
        <table  >
            <tr>
                <th colspan='3'>
                    Contato
                </th>
            </tr>
            <tr>
                <th>
                    ID
                </th>
                <th>
                    Nome
                </th>
                <th>
                    E-mail
                </th>
            </tr>
            <tr>
                <td>
                    <?php echo $o_contato->getId()?>
                </td>
                <td>
                    <?php echo $o_contato->getNome()?>
                </td>
                <td>
                    <?php echo $o_contato->getEmail()?>
                </td>
            </tr>
        </table>
        <br />
        <table width="50%" border="1">
            <tr>
                <th colspan="5">
                    Telefones
                </th>
            </tr>
            <tr>
                <th>
                    ID
                </th>
                <th>
                    DDD
                </th>
                <th>
                    Telefone
                </th>
                <th colspan="2">
                    A&ccedil;&otilde;es
                </th>
            </tr>
            <?php
            foreach($v_telefones AS $o_telefone)
            { 
                ?>
                <tr>
                    <td align="center">
                        <?php echo $o_telefone->getId()?>
                    </td>
                    <td align="center">
                        <?php echo $o_telefone->getDDD()?>
                    </td>
                    <td align="center">
                        <?php echo $o_telefone->getTelefone()?>
                    </td>
                    <td align="center">
                        <a href='?controle=Telefone&acao=apagarTelefone&in_con=<?php echo $o_contato->getId()?>&in_tel=<?php echo $o_telefone->getId()?>'>Apagar</a>
                    </td>
                    <td align="center">
                        <a href='?controle=Telefone&acao=manterTelefone&in_con=<?php echo $o_contato->getId()?>&in_tel=<?php echo $o_telefone->getId()?>'>Editar</a>
                    </td>
                </tr>
                <?php
            } 
            ?>
        </table>
        <br />
        <a href='?controle=Index'>Voltar</a>
        <a href='?controle=Telefone&acao=manterTelefone&in_con=<?php echo $o_contato->getId()?>'>Novo Telefone</a>
    </div>
</body>
</html>
