<?php
$v_params = $this->getParams();
$v_contatos = $v_params['v_contatos'];
?>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>
        Agenda Telef&ocirc;nica
    </title>
    <link rel="stylesheet" type="text/css" href="estilo.css" />
</head>
<body>
    <div id="tblcontc" align="center">
        <table  >
            <tr>
                
                <th>
                    Nome
                </th>
                <th>
                    Empresa
                </th>
                <th colspan="3">
                    A&ccedil;&otilde;es
                </th>
            </tr>
            <?php
            foreach($v_contatos AS $o_contato)
            {
                ?>
                <tr>
                    
                    <td>
                        <?php echo $o_contato->getNome()?>
                    </td>
                    <td>
                        <?php echo $o_contato->getEmail()?>
                    </td>
                    <td align="center">
                        <a href='?controle=Telefone&acao=listarTelefones&in_con=<?php echo $o_contato->getId()?>'>Telefones</a>
                    </td>
                    <td align="center">
                        <a href='?controle=Contato&acao=manterContato&in_con=<?php echo $o_contato->getId()?>'>Editar</a>
                    </td>
                    <td align="center">
                        <a href='?controle=Contato&acao=apagarContato&in_con=<?php echo $o_contato->getId()?>'>Apagar</a>
                    </td>
                </tr>
                <?php
            }
            ?>
        </table>
        <br />
        <a href='?controle=Contato&acao=manterContato'>Novo Contato</a>
    </div>
</body>
</html>
