<?php
$v_params = $this->getParams();
$o_contato = $v_params['o_contato'];
$o_telefone = $v_params['o_telefone'];
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>
        Agenda Telef&ocirc;nica - Exemplo de MVC com PHP
    </title>
    <link rel="stylesheet" type="text/css" href="estilo.css" />
</head>
<body>
    <div id="tblcontc"align="center">
        <table >
            <tr>
                <th colspan='3'>
                    Contato
                </th>
            </tr>
            <tr>
                <th>
                    ID
                </th>
                <th>
                    Nome
                </th>
                <th>
                    E-mail
                </th>
            </tr>
            <tr>
                <td>
                    <?php echo $o_contato->getId()?>
                </td>
                <td>
                    <?php echo $o_contato->getNome()?>
                </td>
                <td>
                    <?php echo $o_contato->getEmail()?>
                </td>
            </tr>
        </table>
        <br />
        <form method='post'>
        <table width="40%" border="1">
            <tr>
                <th colspan="4">
                    Telefones
                </th>
            </tr>
            <tr>
                <th>
                    DDD
                </th>
                <th>
                    Telefone
                </th>
                <th>
                    A&ccedil;&otilde;es
                </th>
            </tr>
            <tr>
                <td align="center">
                    <input type='text' name='in_ddd' value='<?php echo $o_telefone->getDDD()?>' size="5" maxlength="3">
                </td>
                <td align="center">
                    <input type='text' name='in_telefone' value='<?php echo $o_telefone->getTelefone()?>'>
                </td>
                <td align="center">
                    <input type='hidden' name='controle' value='Telefone'>
                    <input type='hidden' name='acao' value='manterTelefone'>
                    <input type='hidden' name='in_con' value='<?php echo $o_contato->getId()?>'>
                    <input type='hidden' name='in_tel' value='<?php echo $o_telefone->getId()?>'>
                    <button type='submit'>Salvar</button>
                </td>
            </tr>
        </table>
        </form>
        <br />
        <a href='?controle=Telefone&acao=listarTelefones&in_con=<?php echo $o_contato->getId()?>'>Cancelar</a>
    </div>
</body>
</html>
